const tagsData = [
    {
        block: 0,
        ownerUsername: "Bitoshi Blockamoto",
        tags: ["bitoshi", "blockamoto", "genesis", "zero", "bitmap.land"],
        imageUrls: ["images/blockamoto/blockamoto-pfp.jpg" ,"images/blockamoto/bitoshi.jpg",],
        websiteUrl: "https://bitmap.land/", 
        TwitterUrl: "blockamoto",
    },
    {
        block: 3,
        ownerUsername: "Metavoxelz",
        tags: ["Metavoxelz", "voxel", "art"],
        imageUrls: ["images/metavoxelz/metavoxelz.jpg"],
        websiteUrl: "https://linktr.ee/metavoxelz",
        TwitterUrl: "Metavoxelz",
    },
    {
        block: 8,
        ownerUsername: "8Bit",
        tags: ["8Bit", "8", "bit", "versions", "recursion", "art", "therecursed", "Ordlibrary", "library", "Decentralized", "Diamond",],
        imageUrls: ["images/8bit/8bit-pfp.jpg", "images/8bit/decentralized-diamond-co.jpg", "images/8bit/bitmap-punk.jpg", "images/8bit/8bit.png", "images/8bit/ordlibrary.jpg"],
        websiteUrl: "https://ordlibrary.com/",
        TwitterUrl: "therecursed",
        bitmapValleyUrl: "yes",
    },
    {
        block: 9,
        ownerUsername: "9.bitmap",
        tags: ["9", "block9ine", "Blix", "music", "art", "nine"],
        imageUrls: ["images/blocknine/9bitmap.jpg" ,"images/blocknine/blix-img.png"],
        websiteUrl: "https://blix.wtf//", 
        TwitterUrl: "block9ine",
    },
    {
        block: 54,
        ownerUsername: "54.bitmap",
        tags: ["jazz"],
        imageUrls: ["images/54bitmap/54jazz.jpg"],
        TwitterUrl: "Jazz32756635599",
    },
    {
        block: 65,
        ownerUsername: "Benbuiz",
        tags: ["ghb.eth", "ghb", "benbuiz"],
        imageUrls: ["images/benbuiz/benbuiz.jpg"],
        imageUrl: "images/benbuiz.jpg",
        TwitterUrl: "benbuiz",
    },
    {
        block: 67,
        ownerUsername: "CRFTD",
        tags: ["CRFTD", "art", "bLOCKHeadz", "City", "Pristine", "Punk" ],
        imageUrls: ["images/crftd.png", "images/crftd/bitmap-city.jpg", "images/crftd/punkmap.jpg",],
        websiteUrl: "https://www.crftdla.com/", 
        TwitterUrl: "_CRFTD_",
    },
    {
        block: 87,
        ownerUsername: "0xValue",
        tags: ["0xValue", "Value0x", "value"],
        imageUrls: ["images/value/value.jpg"],
        TwitterUrl: "Value0x",
    },
    {
        block: 91,
        ownerUsername: "The Block Runner",
        tags: ["Block", "Runner", "Iman", "Will", "Podcast", "YouTube"],
        imageUrls: ["images/blockrunner/tbr-logo.png", "images/blockrunner/blockrunner.png", "images/blockrunner/firstepisode.jpg",],
        websiteUrl: "https://www.theblockrunner.com/",
        YTUrl: "@TheBlockRunner",
        TwitterUrl: "TheBlockRunner",
    },
    {
        block: 100,
        ownerUsername: "iman.sats",
        tags: ["iman.sats", "Iman", "Block", "Runner", "Podcast", "YouTube"],
        imageUrls: ["images/iman/iman.jpg"],
        TwitterUrl: "iman_blockrun",
    },
    {
        block: 108,
        ownerUsername: "Squid Game Club",
        tags: ["Squid Game Club", "Squid", "Game", "DynamikeGuo"],
        imageUrls: ["images/squidgame/squidgame.jpg"],
        TwitterUrl: "DynamikeGuo",
    },
    {
        block: 154,
        ownerUsername: "Apollo11.btc",
        tags: ["Apollo11.btc", "Apollo11", "apollo"],
        imageUrls: ["images/apollo/apollo.jpg"],
        TwitterUrl: "dcfwd",
    },
    {
        block: 171,
        ownerUsername: "A2E - Crypto Investor",
        tags: ["A2E"],
        imageUrls: ["images/A2E/A2E.png"],
        TwitterUrl: "A2E_A2E", 
    },
    {
        block: 353,
        ownerUsername: "NRCHST",
        tags: ["NRCHST", "NRCHST.sats", "NRCHSTx"],
        imageUrls: ["images/nrchst/nrchst.jpg"],
        TwitterUrl: "NRCHSTx",
    },
    {
        block: 382,
        ownerUsername: "madi.x",
        tags: ["madi.x", "madix", "og.bitmap"],
        imageUrls: ["images/madix/madix.jpg"],
        TwitterUrl: "forsure_madix",
    },
    {
        block: 444,
        ownerUsername: "ET",
        tags: ["ET"],
        imageUrls: ["images/et/et.png"],
        TwitterUrl: "444bitmap", 
    },
    {
        block: 502,
        ownerUsername: "999 Club",
        tags: ["999", "Club", "sub", "1K"],
        imageUrls: ["images/999club/999club.jpg"],
        TwitterUrl: "The999Club_",
    },
    {
        block: 505,
        ownerUsername: "axiemaid",
        tags: ["axiemaid", "axie", "bitmap.directory", "directory"],
        imageUrls: ["images/axiemaid/axiemaid.jpg"],
        websiteUrl: "http://bitmap.directory/", 
        TwitterUrl: "axiemaid",
    },
    {
        block: 609,
        ownerUsername: "bop.xbt",
        tags: ["bop.xbt", "bop", "boppleton", "borosilicate", "boropunk", "pixelpunk", "pixel", "punk", "punks", "Three.js", "js"],
        imageUrls: ["images/bop/bop.jpg" ,"images/bop/boropunk.jpg", "images/bop/pixelpunk.jpg"],
        TwitterUrl: "boppleton",
    },
    {
        block: 710,
        ownerUsername: "Boyster",
        tags: ["boyster", "oil"],
        imageUrls: [],
        TwitterUrl: "Boysterbro",
    },
    {
        block: 714,
        ownerUsername: "LostPoet.sats",
        tags: ["LostPoet.sats", "lost", "poet", "music", "musician", "writer"],
        imageUrls: ["images/lostpoet/lostpoet.jpg"],
        TwitterUrl: "LostPoet",
    },
    {
        block: 722,
        ownerUsername: "林冲.btc",
        tags: ["林冲", "jackle_eth", "jackle", "goosinals"],
        imageUrls: ["images/jackle/punk.jpg", "images/jackle/jackle.jpg"],
        TwitterUrl: "jackle_eth",
    },
    {
        block: 733,
        ownerUsername: "Non Fungible Gentleman",
        tags: ["Non Fungible Gentleman", "NftDiscoMan", "NFT", "DiscoMan", "Disco"],
        imageUrls: ["images/nftdiscoman/discoman.jpg"],
        TwitterUrl: "NftDiscoMan", 
    },
    {
        block: 786,
        ownerUsername: "Crypto Fox",
        tags: ["Crypto Fox", "fox", "hotmonkeydeals", "RecursiveX"],
        imageUrls: ["images/cryptofox/cryptofox.jpg"],
        TwitterUrl: "hotmonkeydeals",
    },
    {
        block: 792,
        ownerUsername: "athos",
        tags: ["athos", "espionagesats"],
        imageUrls: ["images/athos/athos.jpg"],
        TwitterUrl: "espionagesats",
    },
    {
        block: 802,
        ownerUsername: "Tomasz.x",
        tags: ["Tomasz.x", "Tomasz"],
        imageUrls: ["images/tomasz/tomasz.jpg"],
        TwitterUrl: "Tomasz__83",
    },
    {
        block: 817,
        ownerUsername: "817.bitmap",
        tags: ["Three", "Cycles", "fightclub.eth", "ENS"],
        imageUrls: ["images/threecycles/threecycles.jpg"],
        TwitterUrl: "ThreeCycles",
    },
    {
        block: 980,
        ownerUsername: "wealth.bitmap",
        tags: ["wealth.bitmap", "wealth", "ordinal.club", "ammdex"],
        imageUrls: ["images/wealth/wealth.jpg"],
        TwitterUrl: "ammdex",
    },
    {
        block: 1051,
        ownerUsername: "BenjaminsCartel.btc",
        tags: ["BenjaminsCartel.btc", "Benjamins", "Cartel", "art", "Ben", "BitArtifacts"],
        imageUrls: ["images/benjaminsCartel/bencartel.jpg", "images/benjaminsCartel/bitartifacts.png"],
        websiteUrl: "https://ordinalswallet.com/collection/benjamins-cartel-btc", 
        TwitterUrl: "3eyondLabs",
    },
    {
        block: 1470,
        ownerUsername: "Nefu.sats",
        tags: ["Nefu.sats", "Nefu",],
        imageUrls: ["images/nefu/nefu-pfp.jpg"],
        TwitterUrl: "0xNefu", 
    },
    {
        block: 1970,
        ownerUsername: "Boyster",
        tags: ["boyster"],
        imageUrls: [],
        TwitterUrl: "Boysterbro", 
    },

    // ... more entries ...
];